### ISSUE TITLE
guidance/input to Apple re: Uniform Type Identifiers for the various ASWF projects 

### ISSUE THREAD

**Issue by drwave** [AcademySoftwareFoundation/tac#541]
### Please share any additional details on this topic

[Uniform Type Identifiers ](https://en.wikipedia.org/wiki/Uniform_Type_Identifier#:~:text=A%20Uniform%20Type%20Identifier%20(UTI,class%20or%20type%20of%20item.) akin to [MIME](https://en.wikipedia.org/wiki/Media_type) types

### Detail what actions or feedback you would like from the TAC

We'd love to get any guidance from the TAC re: this. Should not take long.

### How much time do you need for this topic?

None

**Comment by jmertic** [comment]
Following up - if you can provide a proposal doc I can work to get it ready for the TAC website and to be approved. Thanks!

**Comment by drwave** [comment]
Thanks John. We have something; let me get it up here...

**Comment by dgovil** [comment]
Adding here as a markdown.
Some notes : 

1. We've only included projects with associated file formats in the table below. As such, we've skipped OpenCue, ORI, OpenAssetIO, DPEL, OIIO etc...
2. Where the extension references the Open part of the project name, we've kept it in the identifiers. e.g oil, ocio, otio.
3. Where they don't reference the open part, we coincidentally also have multiple implementations that use the same extension, so we drop the Open part in the identifier to be agnostic.
4. I've included OpenFX in the table below, but I don't believe we should give it a specific identifier because it uses generic dynamic library extensions, and as such shouldn't be associated with an identifier.

| Project               | Extensions    | UTType                         | Media Type                                  | Notes                                                                                                            |
|-----------------------|---------------|--------------------------------|---------------------------------------------|------------------------------------------------------------------------------------------------------------------|
| Open Shading Language | .osl .oso     | io.aswf.openshadinglanguage    | application/vnd.aswf.openshadinglanguage    | .osl is source , .oso is compiled but both are plain text                                                        |
| OpenColorIO           | .ocio         | io.aswf.opencolorio            | application/vnd.aswf.opencolorio            |                                                                                                                  |
| OpenEXR               | .exr          | io.aswf.exr                    | application/vnd.aswf.exr                    | Currently this is `com.ilm.openexr-image` but we can conform the new one to the old one, such that they co-exist |
| OpenVDB               | .vdb          | io.aswf.vdb                    | application/vnd.aswf.vdb                    | VDB extension used by both OpenVDB and NanoVDB                                                                   |
| MaterialX             | .mtlx         | io.aswf.materialx              | application/vnd.aswf.materialx              |                                                                                                                  |
| OpenTimelineIO        | .otio         | io.aswf.opentimelineio         | application/vnd.aswf.opentimelineio         |                                                                                                                  |
| OpenTimelineIO        | .otioz        | io.aswf.opentimelineio-package | application/vnd.aswf.opentimelineio-package |                                                                                                                  |
| OpenFX                | .dll / .dylib | N/A                            | N/A                                         | Skipping this one because the extensions are too commonly used                                                   |

**Comment by darbyjohnston** [comment]
I'm not sure how widely supported it is but OpenTimelineIO also uses the ".otiod" extension for directories that contain an .otio file and associated media:
https://opentimelineio.readthedocs.io/en/stable/tutorials/otio-plugins.html?highlight=otiod#otiod

**Comment by dgovil** [comment]
@darbyjohnston ah good callout. I'll look into how directories are handled by both. 

Afaik MIME/Media doesn't handle directories but UTType might because you can register directories as a bundle type on Apple platforms.

**Comment by dgovil** [comment]
Thanks, @darbyjohnston . I added a UTType for otiod. I don't see a way to do it for MIME types, but UTType supports it.

Questions for some of the folks (just cc'ing who comes to mind first, but anyone please feel free to answer)

1. @meshula , can any application that supports otio also support otioz and otiod?
2. @lgritz , can `.osl` and `.oso` be used interchangeably? Can any application that supports one , support the other?

**Comment by lgritz** [comment]
.oso is not technically part of the OSL spec, it's used by the library. If somebody else wrote an independent implementation of the OSL language, it would read the .osl files of course, but I wouldn't necessarily expect it to use .oso unless they particularly wanted to be able to read compiled shaders that were built with our oslc compiler.

**Comment by dgovil** [comment]
Okay that's good to know. I'll ditch it from the table above

**Comment by lgritz** [comment]
OTOH, the "oslquery" library and "oslinfo" utility to read oso files. I don't have a strong opinion on whether you should care about the oso extension.

**Comment by meshula** [comment]
> can any application that supports otio also support otioz and otiod?

Yes, although it is not transparent like opening a usdz file, an application must take specific action upon encountering such a file.

**Comment by lgritz** [comment]
There seems to be a mix where for some you are using the name of the project (opentimelineio, openshadinglangauge) and others you are using the file extension (exr, vdb). Should be be consistent?

**Comment by dgovil** [comment]
I had called that out in the points above the table. Happy to make them start with open as well, but I wasn't sure if that was the right call. 

- I used Open when the extension starts with an o from the acronym
- VDB is used by both OpenVDB and NanoVDB. Should that be associated with one over the other? 
- EXR also has a few implementations kicking about, like the one Nick put in USD recently. Should we associate it with a specific one?

**Comment by lgritz** [comment]
nanovdb is part of the openvdb project now

I don't have especially strong feelings about it, but my leaning is that the "io.aswf" part indicates that these are meant to be full, formal, maximally unique names, so I think use the correct project name across the board?

I'm not crazy about the "if there is another implementation, switch to the abbreviation" heuristic, because (a) so what, these are the official ones; and (b) that nice rule of thumb is going to become an inconsistent mess as soon as a currently-one-implementation format has a second implementation released after you have carved these things in stone.

**Comment by dgovil** [comment]
That's fair. If nanovdb is considered part of OpenVDB, and not a separate thing, I'll just go ahead and adjust them all to prefix with open.

**Comment by darkvertex** [comment]
@dgovil Hi Dhruv! -- In an earlier comment you wrote in a table that OpenEXR files should have the MIME type (Media Type) of `application/vnd.aswf.openexr` but I just wanted to share that the `shared-mime-info` package from the Freedesktop folks -- which is used by a lot of Linux projects -- already locked-in *.exr type as being `image/x-exr`, as per this line:
https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/091b9b604fd29b622067afb6a69fb63109c978e5/data/freedesktop.org.xml.in#L5432

Personally I think a mimetype starting with `image/` makes a lot more sense as exrs are.. well, images.

---
I'm also not saying that the `shared-mime-info` package is the _ultimate_ authority on the matter, but it is an extremely popular database that a lot of MIME-using codebases (like Gnome Desktop) source their types from already.

Whatever MIME types the ASWF ultimately decides to "officialize" ("popularize"?) might be worth contributing into that package maybe.

**Comment by dgovil** [comment]
Yeah you're right on the money about exr. Our type folks also suggest keeping it as the current ilm version. 

I'll adjust the table above accordingly.

**Comment by meshula** [comment]
I don't think it makes sense to have OpenFX dll/dylib in the table. Those are not file type associations, they are implementation artifacts.

**Comment by dgovil** [comment]
> I don't think it makes sense to have OpenFX dll/dylib in the table. Those are not file type associations, they are implementation artifacts.

Yep, that's why I marked them as N/A. I was just listing all the ASWF projects on the left column to make sure I didn't miss any.

**Comment by meshula** [comment]
Ok, how about putting N/A in the associated file extension column, as it still a fact that dll/dylib are not file extensions associated with OpenFX. It would be nonsense to check all dll/dylib files to discover if they are in fact associated with OpenFX.

**Comment by jmertic** [comment]
Hi @dgovil - anything else needed on this one?

**Comment by dgovil** [comment]
I think we're good here and can close this out. Either you or Michael would have to close it though. 

There are some good points about a different mime type, but for our needs of the UTType, I think we are good.
