### ISSUE TITLE
Using Zoom polling for TAC votes

### ISSUE THREAD

**Issue by jfpanisset** [AcademySoftwareFoundation/tac#702]
### Please share any additional details on this topic

Should we use Zoom polling for TAC votes so we have a more structured way to keep track of these votes?

https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0066150#h_01H9RW67820KFTQ6BT9FRMP8JN

There's currently no way to restrict voting to members with voting rights, so we would need to remind attendees of who should take part in the vote beforehand.

Would be even better if keeping track of vote results could be integrated in the LFX platform.

### Detail what actions or feedback you would like from the TAC

- ask for feedback from the TAC as to whether this is desired
- try a sample vote using the polling feature

### How much time do you need for this topic?

5 minutes or less

**Comment by jmertic** [comment]
The other option is to conduct all votes offline, using the LFX Voting feature ( see https://docs.linuxfoundation.org/lfx/project-control-center/v2-latest-version/collaborations/voting ).

This has come up in other projects, mostly around trying to capture quorum rather than voting. I've not seen huge concerns about voting per se, but mostly because the vast majority of votes are unanimous. I know the LFX team is looking at a solution for quorum.

**Comment by jmertic** [comment]
@jfpanisset Seeing if we should consider doing votes offline to help, or if staying the course makes sense. LMK

**Comment by jfpanisset** [comment]
Closing this for now, until someone comes up with a polling system for zoom which keeps track of who can vote, not sure there's a much better solution.
