### ISSUE TITLE
Add 'aswf-pypi' as owner on PyPi accounts

### ISSUE THREAD

**Issue by jmertic** [AcademySoftwareFoundation/tac#723]
### Please share any additional details on this topic

We want all projects using PyPi to add the user 'aswf-pypi' as an owner on any PyPi projects or organizations for hosted projects.

### Detail what actions or feedback you would like from the TAC

For hosted projects using PyPi, please add the user 'aswf-pypi' as an owner.

### How much time do you need for this topic?

None

**Comment by aclark4life** [comment]
I'd recommend you use organizations instead because in today's world, shared accounts like that are generally frowned upon for a variety of reasons, mostly security-related. Looks like someone just needs to make a request for an ASWF organization.

https://pypi.org/manage/organizations/


![Screenshot 2024-06-10 at 2 03 49 PM](https://github.com/AcademySoftwareFoundation/tac/assets/72164/f8a7af55-065a-48d0-91d5-d6b2335a6b84)

**Comment by tykeal** [comment]
@aclark4life, we requested an organization 2 years ago when they first announced public availability. It's never been completed. We've asked _again_ under this new account. While I agree that role based accounts are generally frowned upon, ASWF is contracted with the Release Engineering organization at LF and as such, we need to have a role account to do this sort of work. We keep access very close managed and generally only use the role to grant the appropriate rights to a named individual.

**Comment by jmertic** [comment]
Closing, added new TAC page to address https://tac.aswf.io/tools/project-accounts.html
